# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
permalink: /:title
# relative_permalinks: true

# Setup
title:            "Jeniusin dengan Jenius"
tagline:          "Jeniusin aja!"
description:      'Jenius untuk semua kebutuhan cashless anda'
url:              https://jenius.in
baseurl: 		      ''
author:
  name:           'Jenius'
  url:            https://jenius.in/
  handle:         "jeniusconnect"
  email:          deden@jenius.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/dedenf/jeniusin

plugins: 
  - jemoji
  - jekyll-paginate
  
paginate_path: "page/:num"
excerpt_separator: "<!--more-->"

pages_list:
  Tentang: '/about'
  Arsip: '/archive'
  Feed: '/atom.xml'

  